#!/bin/bash
# PreToolUse hook for Write|Edit|MultiEdit. Blocks file content matching forbidden
# patterns from CLAUDE.md: emojis, emdashes, attribution lines, legacy model IDs.
# Reads hook input JSON from stdin, emits permissionDecision JSON to stdout.

INPUT=$(cat)
printf '%s' "$INPUT" | python3 -c '
import json, sys, re

try:
    data = json.load(sys.stdin)
except Exception:
    print("{}"); sys.exit(0)

tool = data.get("tool_name", "")
inp  = data.get("tool_input", {})

if tool == "Write":
    content = inp.get("content", "")
elif tool == "Edit":
    content = inp.get("new_string", "")
elif tool == "MultiEdit":
    edits = inp.get("edits", []) or []
    content = "\n".join((e or {}).get("new_string", "") for e in edits)
else:
    print("{}"); sys.exit(0)

if not content:
    print("{}"); sys.exit(0)

reason = None

for needle, msg in [
    ("Co-Authored-By",        "Co-Authored-By attribution forbidden by CLAUDE.md"),
    ("Generated with Claude", "Claude attribution forbidden by CLAUDE.md"),
    ("Generated by Claude",   "Claude attribution forbidden by CLAUDE.md"),
]:
    if needle in content:
        reason = msg; break

if not reason and ("\u2014" in content or "\u2013" in content):
    reason = "Emdash/endash forbidden by CLAUDE.md - use hyphens or rewrite"

if not reason:
    if re.search(r"gpt-4o|gpt-4\.1|gpt-3\.5|gpt-4(?![\.\-\d])|claude-3-(opus|sonnet|haiku)", content):
        reason = "Legacy model ID forbidden by CLAUDE.md - use latest model versions only"

if not reason:
    for ch in content:
        cp = ord(ch)
        if (0x1F300 <= cp <= 0x1FAFF) or (0x1F600 <= cp <= 0x1F64F) or (0x1F680 <= cp <= 0x1F6FF) or cp == 0x1F916:
            reason = "Emoji (" + repr(ch) + ") forbidden by CLAUDE.md"; break

if reason:
    print(json.dumps({
        "hookSpecificOutput": {
            "hookEventName": "PreToolUse",
            "permissionDecision": "deny",
            "permissionDecisionReason": "BLOCKED: " + reason
        }
    }))
else:
    print("{}")
'
