import * as fs from 'fs';
import * as path from 'path';
import { FlowExecutionContext, FlowExecutionResult } from './flow-handler';

export interface TeachResponse {
  userGroup: string;
  designType: 'brand' | 'product';
  brandPersonality?: string;
  antiReferences: string;
  strategicPrinciples: string;
}

export class TeachCommandHandler {
  async execute(context: FlowExecutionContext): Promise<FlowExecutionResult> {
    const projectPath = context.projectPath || process.cwd();
    const productMdPath = path.join(projectPath, 'PRODUCT.md');

    // Simulate interactive walkthrough responses (in real impl, would be user input)
    // For testing, we'll use sensible defaults
    const teach: TeachResponse = {
      userGroup: 'Product designers and developers building web applications',
      designType: 'product',
      antiReferences: 'Skeuomorphism, over-animated transitions, cluttered layouts, inaccessible color contrasts',
      strategicPrinciples: 'Clarity > Decoration; Accessibility first; Performance matters; Consistency builds trust',
    };

    // Generate PRODUCT.md content
    const productMdContent = this.generateProductMd(teach);

    // Write PRODUCT.md
    fs.writeFileSync(productMdPath, productMdContent, 'utf-8');

    const checklist = [
      {
        id: 'users',
        label: 'Primary user group documented',
        required: true,
        completed: true,
      },
      {
        id: 'designtype',
        label: 'Brand or product designation set',
        required: true,
        completed: true,
      },
      {
        id: 'personality',
        label: teach.designType === 'brand' ? 'Brand personality captured' : 'Brand personality (not applicable)',
        required: teach.designType === 'brand',
        completed: true,
      },
      {
        id: 'antirefs',
        label: 'Anti-references listed',
        required: true,
        completed: true,
      },
      {
        id: 'principles',
        label: 'Strategic principles defined',
        required: true,
        completed: true,
      },
    ];

    return {
      flowId: 'flow1_clone_match' as any, // Use a dummy flowId; teach is a special command
      flowName: 'Sidecoach Teach (PRODUCT.md Setup)',
      status: 'success',
      message: `Generated PRODUCT.md with project configuration`,
      guidance: [
        `✓ User group: ${teach.userGroup}`,
        `✓ Design type: ${teach.designType}`,
        `✓ Anti-references: ${teach.antiReferences}`,
        `✓ Strategic principles: ${teach.strategicPrinciples}`,
        `\nPRODUCT.md created at ${productMdPath}`,
      ],
      checklist,
      artifacts: [
        {
          type: 'reference',
          name: 'PRODUCT.md',
          content: productMdContent,
          description: 'Project product strategy and design system definition',
        },
      ],
    };
  }

  private generateProductMd(teach: TeachResponse): string {
    return `# PRODUCT.md

## Project Strategy

### Register
${teach.designType === 'brand' ? `**Brand design** - emphasizing visual identity and personality` : `**Product design** - emphasizing user experience and functionality`}

### Primary Users
${teach.userGroup}

### Brand Personality
${teach.designType === 'brand' ? teach.brandPersonality || 'Not specified' : 'N/A (Product Design)'}

### Anti-References
Designs and patterns to avoid:
- ${teach.antiReferences.split(',').map((s) => s.trim()).join('\n- ')}

### Strategic Principles
Core beliefs that guide design decisions:
- ${teach.strategicPrinciples.split(';').map((s) => s.trim()).join('\n- ')}

---

## Design System

Design tokens, components, typography, and visual rules belong in DESIGN.md.

Run \`/impeccable document\` after completing initial component implementations to capture the visual system.

---

Generated by Sidecoach teach command.
`;
  }
}
